---
- name: create aws ec2 instances
  hosts: local
  connection: local
  tasks:
    - name: create key pair
      ec2_key:
        name: ansiblekey1
        region: eu-west-1
      register: ansiblekey1

    - name: save ansiblekey1 on localhost
      copy: content="{{ ansiblekey1.key.private_key }}" dest="./ansiblekey1.pem" mode=0600
      when: ansiblekey1.changed

    - name: create security group for buildinstance
      ec2_group:
        name: buildinstance
        description: for build-instance
        region: eu-west-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: create security group for deployinstance
      ec2_group:
        name: deployinstance
        description: for deploy-instance
        region: eu-west-1
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

    - name: create vpc
      ec2_vpc_net:
        name: homework
        cidr_block: 172.30.0.0/16
        region: eu-west-1
        tags:
          module: ec2_vpc_net
          this: works
      register: homework
#        tennacy: dedicated

    - name: create subnet for buildinstance
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc-0eafb1c8d44d5232d
        cidr: 172.30.1.0/24
        resource_tags:
          Name: buildinstance subnet
      register: buildinstance_subnet

    - name: create subnet for deployinstance
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc-0eafb1c8d44d5232d
        cidr: 172.30.2.0/24
        resource_tags:
          Name: deployinstance subnet
      register: deployinstance_subnet

    - name: create buildinstance
      ec2:
        key_name: ansiblekey1
        instance_type: t2.micro
        image: ami-0dc8d444ee2a42d8a
        region: eu-west-1
        wait: yes
        group: buildinstance
        count: 1
        vpc_subnet_id: buildinstance_subnet
        assign_public_ip: yes

    - name: create deployinstance
      ec2:
        key_name: ansiblekey1
        instance_type: t2.micro
        image: ami-0dc8d444ee2a42d8a
        region: eu-west-1
        wait: yes
        group: deployinstance
        count: 1
        vpc_subnet_id: deployinstance_subnet
        assign_public_ip: yes