---
- name: create aws ec2 instances
  hosts: local
  connection: local
  tasks:
    - name: create key pair
      ec2_key:
        name: ansiblekey1
        region: eu-west-1
      register: ansiblekey1

    - name: save ansiblekey1 on localhost
      copy: content="{{ ansiblekey1.key.private_key }}" dest="./ansiblekey1.pem" mode=0600
      when: ansiblekey1.changed

    - name: create security group for buildinstance
      ec2_group:
        name: buildinstance
        description: for build-instance
        region: eu-west-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: create security group for deployinstance
      ec2_group:
        name: deployinstance
        description: for deploy-instance
        region: eu-west-1
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

    - name: create vpc
      ec2_vpc_net:
        name: homework
        cidr_block: 172.30.0.0/16
        region: eu-west-1
        tags:
          module: ec2_vpc_net
          this: works
      register: homework

    - name: create subnet for buildinstance
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ homework.vpc.id }}"
        cidr: 172.30.1.0/24
        resource_tags:
          Name: buildinstance subnet
      register: buildinstance_subnet

    - name: create subnet for deployinstance
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ homework.vpc.id }}"
        cidr: 172.30.2.0/24
        resource_tags:
          Name: deployinstance subnet
      register: deployinstance_subnet

    - name: create buildinstance
      ec2:
        key_name: ansiblekey1
        instance_type: t2.micro
        image: ami-0dc8d444ee2a42d8a
        region: eu-west-1
        wait: yes
        count: 1
        vpc_subnet_id: "{{ buildinstance_subnet.subnet.id }}"
        assign_public_ip: yes
        instance_tags:
          Name: buildinstance
      register: buildinstance
#      count_tag:
#        Name: buildinstance
#      exact_count: 1

    - name: create deployinstance
      ec2:
        key_name: ansiblekey1
        instance_type: t2.micro
        image: ami-0dc8d444ee2a42d8a
        region: eu-west-1
        wait: yes
        count: 1
        vpc_subnet_id: "{{ deployinstance_subnet.subnet.id }}"
        assign_public_ip: yes
        instance_tags:
          Name: deployinstance
      register: deployinstance
#      count_tag:
#        Name: deployinstance
#      exact_count: 1

- name: prepare instance for build
  hosts: 18.202.217.112
  become: yes
  tasks:

    - name: ensure maven is present
      apt:
        name: maven
        state: present

    - name: ensure git is present
      apt:
        name: git
        state: present

    - name: clone boxfuse git repository
      git:
        repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
        dest: /root/
        clone: no

    - name: build the project
      shell: mvn -f boxfuse-sample-java-war-hello/pom.xml package

    - name: fetch war to server
      fetch:
        src: /root/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /tmp/
        flat: yes

- name: run war in deployinstance
  hosts: 54.246.33.224
  become: yes

  tasks:
    - name: ensure tomcat is present
      apt:
        name: tomcat9
        state: present

    - name: ensure tomcat is started
      service:
        name: tomcat9
        state: started

    - name: copy war to prod
      copy:
        src: /tmp/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/