---
- name: create aws ec2 instances
  hosts: local
  connection: local
  tasks:
    - name: create key pair
      ec2_key:
        name: ansiblekey1
        region: eu-west-1
      register: ansiblekey1

    - name: save ansiblekey1 on localhost
      copy: content="{{ ansiblekey1.key.private_key }}" dest="./ansiblekey1.pem" mode=0600
      when: ansiblekey1.changed

    - name: create security group for buildinstance
      ec2_group:
        name: buildinstance
        description: for build-instance
        region: eu-west-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: create security group for deployinstance
      ec2_group:
        name: deployinstance
        description: for deploy-instance
        region: eu-west-1
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

    - name: create vpc
      ec2_vpc:
      register: vpc
        state: present
        cidr_block: 172.30.30.0/24
        resource_tags: { "homework" }
        region: us-west-1
        subnets:
          - cidr: 172.30.30.11/32
            az: us-west-1a
            resource_tags: { "homework","build" }
          - cidr: 172.30.30.12/32
            az: us-west-1a
            resource_tags: { "homework","deploy" }
        internet_gateway: True
        route_tables:
          - subnets:
              - 172.30.30.11/32
              - 172.30.30.12/32
            routes:
              - dest: 0.0.0.0/0
                gw: igw

    - name: create buildinstance
      ec2:
        key_name: ansiblekey1
        instance_type: t2.micro
        image: ami-0dc8d444ee2a42d8a
        region: eu-west-1
        wait: yes
        group: buildinstance
        count: 1
        vpc_subnet_id: build
        assign_public_ip: yes

    - name: create deployinstance
      ec2:
        key_name: ansiblekey1
        instance_type: t2.micro
        image: ami-0dc8d444ee2a42d8a
        region: eu-west-1
        wait: yes
        group: deployinstance
        count: 1
        vpc_subnet_id: deploy
        assign_public_ip: yes